---
# Download ISOs

- block:
    - name: download distros artifacts
      include_role:
        name: amtega.artifact
      vars:
        artifact_list: >-
          {{ lookup('template', 'artifacts.yml.j2') | from_yaml }}

    - name: setup fact with downloads result
      include_role:
        name: amtega.select_hostvars
      vars:
        select_hostvars_pattern: "artifact_result_.*"
        select_hostvars_attributes: [ changed ]
        select_hostvars_fact_name: cobbler_download_isos_result
        select_hostvars_output_type: dict

    - name: update cobbler signatures
      command: cobbler signature update
      register: cobbler_signature_update_result
      failed_when: >-
        '*** TASK COMPLETE ***' not in cobbler_signature_update_result.stdout
      when: >-
        cobbler_download_isos_result.values()
        | selectattr('changed') | list | length > 0
        or cobbler_umount_stalled_isos is changed
      notify:
        - synchronize cobbler
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::isos
    - role::cobbler::configure::distros::isos::download
