---
# Download ISOs

- block:
    - name: download ISOs
      include_role:
        name: amtega.artifact
      vars:
        override:
          id: "{{ cobbler_distro_artifact_id }}"
          dest: "{{ cobbler_iso_dir }}/{{ cobbler_distro.artifact.dest }}"
        artifact: "{{ dobbler_distro.artifact | combine(override) }}"
      when: >
        dobbler_distro.state == "present"
        and dobbler_distro.name not in cobbler_saved_isos
      loop: "{{ cobbler_distros }}"
      loop_control:
        loop_var: dobbler_distro
        label: "{{ dobbler_distro.artifact.file }}"

    - name: update cobbler signatures
      command: cobbler signature update
      environment: "{{ proxy_client_environment }}"
      register: cobbler_signature_update_result
      failed_when: >-
        '*** TASK COMPLETE ***' not in cobbler_signature_update_result.stdout
      when: >-
        lookup('vars',
               'artifact_result_' + cobbler_distro_artifact_id)['changed']
        or cobbler_umount_stalled_isos | changed
      notify:
        - synchronize cobbler
  vars:
    cobbler_distro_artifact_id: >-
      cobbler_{{ dobbler_distro.name
                 | regex_replace(" ", "")
                 | regex_replace("-", "_") }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::isos
    - role::cobbler::configure::distros::isos::download
