---
# Search ISOs

- name: search iso files
  find:
    paths: "{{ cobbler_iso_dir }}"
    file_type: file
  register: cobbler_search_iso_files_result
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::isos
