---
# Configure distros tasks

- block:

  - name: create temporary mount dir for ISO
    file:
      path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: search free loopback device
    command: losetup -f
    register: cobbler_losetup_result
    failed_when: cobbler_losetup_result.rc != 0

  - debug: msg="{{ cobbler_losetup_result.stdout }}"

  - name: create loopback device
    command: >
      mknod -m 0600 {{ cobbler_losetup_result.stdout }}
      b
      7
      {{ cobbler_losetup_result.stdout | regex_replace("/dev/loop", "") }}
    creates: "{{ cobbler_losetup_result.stdout }}"
    register: cobbler_mknod_result
    failed_when: cobbler_mknod_result.rc != 0

  - name: mount ISO in temporary dir
    mount:
      fstype: iso9660
      opts: "loop,ro"
      src: "{{ cobbler_iso_file }}"
      path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}"
      state: mounted

  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
