---
# Configuration tasks

- name: configure clobber settings
  include: configure_settings.yml
  static: false
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings

- name: configure clobber distros
  include: configure_distros.yml
  static: false
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros

- name: configure clobber profles
  include: configure_profiles.yml
  static: false
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::profiles
