---
# Configure distros tasks

- block:

  - name: create temporary mount dir for ISO
    file:
      path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}"
      state: directory
      owner: root
      group: root
      mode: 0755

  - block:
    - name: mount ISO in temporary dir
      mount:
        fstype: iso9660
        opts: "loop,ro"
        src: "{{ cobbler_iso_file }}"
        path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}"
        state: mounted

    rescue:
    - name: search last used loopback device number
      shell: >-
        losetup -a
        | cut -f1 -d':'
        | tail -1
        | sed -r 's#.*([0-9]+)#\1#g'
      register: cobbler_losetup_result
      failed_when: cobbler_losetup_result.rc != 0
      changed_when: false

    - name: create loopback device
      command: >
        mknod -m 0600
        /dev/loop{{ cobbler_losetup_result.stdout | int + 1 }}
        b
        7
        {{ cobbler_losetup_result.stdout }}
      args:
        creates: "/dev/loop{{ cobbler_losetup_result.stdout | int + 1 }}"
      register: cobbler_mknod_result
      failed_when: cobbler_mknod_result.rc != 0

  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
