---
#  Setup cobbler config files

- block:

  - name: configure /etc/cobbler/settings
    template: src=settings.j2 dest=/etc/cobbler/settings owner=root group=root mode=0644 backup=yes
    notify:
      - synchronize cobbler

  - name: configure /etc/cobbler/modules.conf
    template: src=modules.conf.j2 dest=/etc/cobbler/modules.conf owner=root group=root mode=0644 backup=yes
    notify:
      - synchronize cobbler

  - name: configure /etc/debmirror.conf
    template: src=debmirror.conf.j2 dest=/etc/debmirror.conf owner=root group=root mode=0644 backup=yes
    notify:
      - synchronize cobbler

  - meta: flush_handlers

  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings
