---
# Configuration tasks

- block:
  - name: configure cobbler settings
    include_tasks: configure_settings.yml

  # It's necessary to start cobbler service because  distros and profiles config
  # commands require the service be started

  - name: start cobblerd service
    include_tasks: service.yml

  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings

- name: configure cobbler distros
  include_tasks: configure_distros.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros

# - name: configure cobbler profles
#   include_tasks: configure_profiles.yml
#   tags:
#     - role::cobbler
#     - role::cobbler::configure
#     - role::cobbler::configure::profiles
