---
# Install tasks

- name: install packages needed by cobbler
  package:
    name: "{{ item  }}"
    state: present
  with_items: "{{ cobbler_packages | default([]) }}"
  tags:
    - role::cobbler
    - role::cobbler::packages
    - role::cobbler::install

- block:

  - name: create config directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    with_items:
      - "{{ cobbler_tmp_dir }}"
      - "{{ cobbler_iso_dir }}"
      - "{{ cobbler_iso_mount_dir }}"

  tags:
    - role::cobbler
    - role::cobbler::install
