---
# Role tasks

- name: install cobbler
  include_tasks: main/install.yml
  tags:
    - role::cobbler
    - role::cobbler::install

- name: configure cobbler
  include_tasks: configure/main.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::service
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::cleanup
    - role::cobbler::configure::distros::isos
    - role::cobbler::configure::distros::isos::cleanup
    - role::cobbler::configure::distros::isos::download
