---
# Role tasks

- name: install clobber
  include: install.yml
  static: false
  tags:
    - role::clobber
    - role::clobber::install

- name: configure clobber
  include: configure.yml
  static: false
  tags:
    - role::clobber
    - role::clobber::configure

- name: setup clobber clobber
  include: service.yml
  static: false
  tags:
    - role::clobber
    - role::clobber::service
