---
# Role tasks

- name: install cobbler
  include_tasks: install.yml
  tags:
    - role::cobbler
    - role::cobbler::install

- name: configure cobbler
  include_tasks: configure.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings

- name: enable cobbler service
  include_tasks: service.yml
  tags:
    - role::cobbler
    - role::cobbler::service

- name: setup cobbler distros
  include_tasks: setup_distros.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::distros

# - name: configure cobbler profles
#   include_tasks: setup_profiles.yml
#   tags:
#     - role::cobbler
#     - role::cobbler::configure
#     - role::cobbler::profiles
