---
# Role tasks

- name: install cobbler
  include_tasks: install.yml
  tags:
    - role::cobbler
    - role::cobbler::install

- name: configure cobbler
  include_tasks: configure.yml
  tags:
    - role::cobbler
    - role::cobbler::configure

- name: setup cobbler cobbler
  include_tasks: service.yml
  tags:
    - role::cobbler
    - role::cobbler::service
