---
# Service tasks

- block:

  - name: enable and start cobblerd service
    service:
      name: cobblerd
      state: started
      enabled: yes

  - name: download cobbler loaders
    command: cobbler get-loaders
    environment:
      http_proxy: "{{ cobbler_internet_proxy_http }}"
      https_proxy: "{{ cobbler_internet_proxy_https }}"
    register: cobbler_rsync_result
    changed_when: "'downloading ' in cobbler_rsync_result.stdout"

  - name: check cobbler
    command: cobbler check
    register: cobbler_check_result
    failed_when: >
      'No configuration problems found' not in cobbler_check_result.stdout
    changed_when: false

tags:
  - role::cobbler
  - role::cobbler::service
