---
# Role handlers

- name: Restart cobbler daemon
  service:
    name: cobblerd
    state: restarted
  listen:
    - restart cobblerd
  tags:
    - role::cobbler
    - role::cobbler::service
    - role::cobbler::service::cobblerd

- name: Synchronize cobbler
  command: cobbler sync
  listen:
    - synchronize cobbler
  tags:
    - role::cobbler
    - role::cobbler::service
    - role::cobbler::synchronize
