---
# Role handlers

- name: cobbler restart daemon
  service:
    name: cobblerd
    state: restarted
  listen:
    - restart cobblerd
  tags:
    - role::cobbler
    - role::cobbler::service
    - role::cobbler::service::cobblerd

- name: cobbler synchronize
  command: cobbler sync
  listen:
    - synchronize cobbler
  tags:
    - role::cobbler
    - role::cobbler::service
    - role::cobbler::synchronize

- name: cobbler update signatures
  command: cobbler signature update
  environment:
    http_proxy: "{{ cobbler_internet_proxy_http }}"
    https_proxy: "{{ cobbler_internet_proxy_https }}"
  register: cobbler_signature_update_result
  failed_when: >-
    '*** TASK COMPLETE ***' not in cobbler_signature_update_result.stdout
  listen:
    - update cobbler signatures
  notify:
    - restart cobblerd
  tags:
    - role::cobbler
    - role::cobbler::service
    - role::cobbler::signatures
