---
# Cleanup distros

- block:
    - name: delete unnecesary distros
      command: >-
        cobbler distro remove \
        --name={{ cobbler_saved_iso }}
        --recursive
      when:
        cobbler_saved_iso in cobbler_absent_distros_names
        or (cobbler_delete_unmanaged
            and cobbler_saved_iso not in cobbler_present_distros_names)
      loop: "{{ cobbler_saved_isos.keys() }}"
      loop_control:
        loop_var: cobbler_saved_iso
        label: "{{ cobbler_saved_iso }}"

    - name: delete distros not defined in inventory or with with bad checksums
      command: >-
        cobbler distro remove --name={{ cobbler_saved_iso }} --recursive
      when:
        - cobbler_saved_iso in cobbler_present_distros_names
        - >-
          cobbler_saved_isos[cobbler_saved_iso]['iso_checksum'] | default('')
          != cobbler_distro_iso_ckecksum
      loop: "{{ cobbler_saved_isos.keys() }}"
      loop_control:
        loop_var: cobbler_saved_iso
        label: "{{ cobbler_saved_iso }}"
  vars:
    cobbler_present_distros_names: >-
        {{ cobbler_distros
           | selectattr('state', 'equalto', 'present')
           | map(attribute='name')
           | list }}

    cobbler_absent_distros_names: >-
        {{ cobbler_distros
           | selectattr('state', 'equalto', 'absent')
           | map(attribute='name')
           | list }}

    cobbler_artifact_result_fact: >-
      artifact_result_cobbler_{{ cobbler_saved_iso
                 | regex_replace(" ", "")
                 | regex_replace("-", "_") }}

    cobbler_distro_iso_ckecksum: >-
      {{ cobbler_download_isos_result[cobbler_artifact_result_fact].checksum }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::cleanup
