---
# Import distros

- block:
    - name: Setup fact with distros ISO artifacts
      set_fact:
        cobbler_distros_artifacts: >-
          {{ lookup("template", "artifacts.yml.j2") | from_yaml }}

    - name: Download distros ISO artifacts
      include_role:
        name: amtega.artifact
      vars:
        artifact_list: "{{ cobbler_distros_artifacts }}"

    - name: Create temporary mount directories for ISO files
      file:
        path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_distro.artifact.file }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      register: cobbler_create_mount_dirs_result
      loop: "{{ cobbler_updated_distros.values() | list }}"
      loop_control:
        loop_var: cobbler_distro
        label: "{{ cobbler_distro.name }}"

    - name: Mount ISO files in temporary directories
      mount:
        fstype: iso9660
        opts: "loop,ro"
        src: >-
          {{ [ cobbler_iso_dir,
               cobbler_distro.artifact.dest | default(""),
               cobbler_distro.artifact.file ] | join("/") }}
        path: "{{ cobbler_iso_mount_dir }}/{{ cobbler_distro.artifact.file }}"
        state: mounted
      register: cobbler_mount_isos_result
      loop: "{{ cobbler_updated_distros.values() | list }}"
      loop_control:
        loop_var: cobbler_distro
        label: "{{ cobbler_distro.name }}"

    - name: Update cobbler signatures
      command: cobbler signature update
      register: cobbler_signature_update_result
      failed_when: >-
        '*** TASK COMPLETE ***' not in cobbler_signature_update_result.stdout
      when: >-
        artifact_result.values()
        | select("changed")
        | list
        | length > 0
      notify:
        - restart cobblerd

    - meta: flush_handlers

    - name: Import distros
      command: >-
        cobbler import
        --name={{ cobbler_distro.name }}
        --path={{ cobbler_iso_mount_dir }}/{{ cobbler_distro.artifact.file }}
      register: cobbler_import_result
      loop: "{{ cobbler_updated_distros.values() | list }}"
      loop_control:
        loop_var: cobbler_distro
        label: "{{ cobbler_distro.name }}"

    - name: Add ksmeta attributes to distros config
      command: >-
        cobbler distro edit
        --name={{ cobbler_distro.name }}
        --ksmeta='iso_file={{ cobbler_distro.artifact.file }}'
      when: cobbler_import_result.results[cobbler_distro_index] is changed
      register: cobbler_add_ksmeta_result
      loop: "{{ cobbler_updated_distros.values() | list }}"
      loop_control:
        loop_var: cobbler_distro
        index_var: cobbler_distro_index
        label: "{{ cobbler_distro.name }}"

    - name: Umount distros ISO files from temporary directories
      mount:
        fstype: iso9660
        opts: "loop,ro"
        src: "{{ cobbler_iso_file }}"
        name: "{{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}"
        state: unmounted
      register: cobbler_umount_isos_result
      loop: >-
        {{ cobbler_search_iso_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_iso_file

    - include_tasks: cleanup.yml
      when:
        (artifact_result.values() | list
         + cobbler_create_mount_dirs_result.results
         + cobbler_mount_isos_result.results
         + cobbler_import_result.results
         + cobbler_add_ksmeta_result.results
         + cobbler_umount_isos_result.results)
        | select('changed')
        | list
        | length > 0
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
