---
# Import distros

- block:
    - name: import distros
      command: >-
        cobbler import
        --name={{ cobbler_distro_name }}
        --path={{ cobbler_iso_mount_dir }}/{{ cobbler_iso_file | basename }}
      when: >
        cobbler_distros
        | selectattr('artifact.file', 'equalto', cobbler_iso_file | basename)
        | map(attribute='name')
        | list
        | first
        not in cobbler_saved_isos
      loop: >-
        {{ cobbler_search_iso_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_iso_file

    - name: add ksmeta attributes to distros config
      command: >-
        cobbler distro edit
        --name={{ cobbler_distro_name }}
        --ksmeta='iso_file={{ cobbler_distro_file }}
                  iso_checksum={{ cobbler_distros
                                  | selectattr('artifact.file',
                                               'equalto',
                                                cobbler_iso_file | basename)
                                  | map(attribute='iso_checksum')
                                  | list
                                  | first }}'
      when: >-
        cobbler_distros
        | selectattr('artifact.file', 'equalto', cobbler_iso_file | basename)
        | map(attribute='name')
        | list
        | first
        not in cobbler_already_configure_distros_names
      loop: >-
        {{ cobbler_search_iso_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_iso_file

    - name: delete default profile created during distro import
      command: >-
        cobbler profile remove
        --name={{ cobbler_distro_name }}
        --recursive
      when: >
        cobbler_distros
        | selectattr('artifact.file', 'equalto', cobbler_iso_file | basename)
        | map(attribute='name')
        | list
        | first
        not in cobbler_already_configure_distros_names
      loop: >-
        {{ cobbler_search_iso_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_iso_file
        label: "{{ cobbler_iso_file | basename }}"
  vars:
    cobbler_matched_distros: >-
      {{ cobbler_distros
         | selectattr('artifact.file',
                      'equalto',
                      cobbler_iso_file | basename) }}

    cobbler_distro_name: >-
      {{ cobbler_matched_distros
         | map(attribute='name')
         | list
         | first }}

    cobbler_distro_file: >-
      {{ cobbler_matched_distros
         | map(attribute='artifact.file')
         | list
         | first  }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
