---
# Configure distros tasks

- block:
    - include_tasks: clean.yml
    - include_tasks: import.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
    - role::cobbler::configure::distros::cleanup
