---
# Read distros config

- block:
    - name: Search distros ISO files
      find:
        paths: "{{ cobbler_iso_dir }}"
        file_type: file
      register: cobbler_search_iso_files_result

    - name: Search distros ISO files directories
      command: >-
        find {{ cobbler_iso_dir }}/mounted -mindepth 1 -maxdepth 1 -type d
      register: cobbler_search_iso_tmp_dirs_result
      changed_when: no

    - name: Search distros config files
      find:
        paths: "{{ cobbler_config_dir }}/distros"
        file_type: file
      register: cobbler_search_distro_config_files_result

    - name: Read distros config files
      shell: "cat {{ cobbler_distro_config_file }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_distros_config_result
      changed_when: no
      loop: >-
        {{ cobbler_search_distro_config_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_distro_config_file

    - name: Setup fact with saved distros info
      set_fact:
        _cobbler_saved_distros: >-
          {{ lookup('template', 'saved_distros.yml.j2') | from_yaml }}

    - name: Setup fact with updated distros info
      set_fact:
        _cobbler_updated_distros: >-
          {{ lookup('template', 'updated_distros.yml.j2') | from_yaml }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
