---
# Read distros config

- block:
    - name: search distros ISO files
      find:
        paths: "{{ cobbler_iso_dir }}"
        file_type: file
      register: cobbler_search_iso_files_result

    - name: search distros ISO files directories
      command: >-
        find {{ cobbler_iso_dir }}/mounted -mindepth 1 -maxdepth 1 -type d
      register: cobbler_search_iso_tmp_dirs_result
      changed_when: false

    - name: search distros config files
      find:
        paths: "{{ cobbler_config_dir }}/distros.d"
        file_type: file
      register: cobbler_search_distro_config_files_result

    - name: read distros config files
      shell: "cat {{ cobbler_distro_config_file }}"
      register: cobbler_read_distros_config_result
      changed_when: false
      loop: >-
        {{ cobbler_search_distro_config_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_distro_config_file
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::distros
