---
# Cleanup systems

- block:
    - include_tasks: read.yml

    - name: delete systems to be updated or not found in inventory
      command: >-
        cobbler system remove \
        --name={{ cobbler_saved_system.name }}
        --recursive
      when:
        cobbler_saved_system.name in cobbler_absent_systems_names
        or (cobbler_delete_unmanaged
            and cobbler_saved_system.name not in cobbler_present_systems_names)
        or cobbler_saved_system.name in cobbler_updated_systems.keys() | list
      register: cobbler_delete_systems_result
      loop: "{{ cobbler_saved_systems.values() | list }}"
      loop_control:
        loop_var: cobbler_saved_system
        label: "{{ cobbler_saved_system.name }}"
      vars:
        cobbler_present_systems_names: >-
            {{ cobbler_systems
               | selectattr('state', 'equalto', 'present')
               | map(attribute='name')
               | list }}

        cobbler_absent_systems_names: >-
            {{ cobbler_systems
               | selectattr('state', 'equalto', 'absent')
               | map(attribute='name')
               | list }}

    - include_tasks: read.yml
      when:
        cobbler_delete_systems_result.results
        | select('changed')
        | list
        | length > 0
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::systems
