---
# Configure systems tasks

- block:
    - include_tasks: clean.yml
    - include_tasks: add.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::systems
    - role::cobbler::configure::systems::cleanup
