---
# Read systems

- block:
    - name: Search systems config files
      find:
        paths: "{{ cobbler_config_dir }}/systems.d"
        file_type: file
      register: cobbler_search_systems_config_files_result

    - name: Read systems config files
      shell: "cat {{ cobbler_system_config_file }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_systems_config_result
      changed_when: no
      loop: >-
        {{ cobbler_search_systems_config_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_system_config_file

    - name: Setup facts with systems info
      set_fact:
        _cobbler_saved_systems: >-
          {{ lookup('template', 'saved_systems.yml.j2') | from_yaml }}
        _cobbler_updated_systems: >-
          {{ lookup('template', 'updated_systems.yml.j2') | from_yaml }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::systems
