---
# Add profiles

- block:
    - name: Create profiles autoinstall files
      copy:
        dest: >-
          {{ cobbler_autoinstall_templates_dir }}/{{ cobbler_autoinstall_file }}
        content: "{{ cobbler_profile.autoinstall_content }}"
        mode: 0755
      register: cobbler_autoinstall_add_result
      when: cobbler_profile.autoinstall_content is defined
      loop: "{{ _cobbler_updated_profiles.values() | list }}"
      loop_control:
        loop_var: cobbler_profile
        label: "{{ cobbler_profile.name }}"

    - name: Add profiles
      command: >-
        cobbler profile add
        --name={{ cobbler_profile.name }}
        --distro={{ cobbler_profile.distro }}
        --kernel-options="{{ cobbler_profile_kernel_options }}"
        {{ (cobbler_profile_autoinstall | length > 0)
           | ternary("--autoinstall=" + cobbler_profile_autoinstall, "") }}
        {{ (cobbler_profile.parent | default('') | length > 0)
           | ternary("--parent=" + cobbler_profile.parent | default(''), "") }}
        {{ (cobbler_profile.proxy | default('') | length > 0)
           | ternary("--proxy=" + cobbler_profile.proxy | default(''), "") }}
      register: cobbler_profile_add_result
      loop: "{{ _cobbler_updated_profiles.values() | list }}"
      loop_control:
        loop_var: cobbler_profile
        label: "{{ cobbler_profile.name }}"
      vars:
        cobbler_profile_autoinstall: >-
          {{ (cobbler_profile.autoinstall_content | default("") | length > 0)
             | ternary(cobbler_autoinstall_file,
                       (cobbler_profile.autoinstall | default("") | length > 0)
                       | ternary(cobbler_profile.autoinstall, "")) }}
        cobbler_profile_kernel_options: >-
          {{ lookup('template', 'kernel_options.yml.j2') | from_yaml }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::profiles
