---
# Configure profiles tasks

- block:
    - include_tasks: clean.yml
    - include_tasks: add.yml
  vars:
    cobbler_autoinstall_file: "profile_{{ cobbler_profile.name }}.ks"
    cobbler_autoinstall_file_path: >-
      {{ cobbler_autoinstall_templates_dir }}/{{ cobbler_autoinstall_file }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::profiles
    - role::cobbler::configure::profiles::cleanup
