---
# Read profiles

- block:
    - name: Search profiles config files
      find:
        paths: "{{ cobbler_config_dir }}/profiles.d"
        file_type: file
      register: cobbler_search_profiles_config_files_result

    - name: Read profiles config files
      shell: "cat {{ cobbler_profile_config_file }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_profiles_config_result
      changed_when: no
      loop: >-
        {{ cobbler_search_profiles_config_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_profile_config_file
        label: "{{ (cobbler_profile_config_file | basename | splitext).0 }}"

    - name: Read profiles kickstart files
      shell: "cat {{ cobbler_kickstart_file_path }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_kickstarts_result
      failed_when: no
      changed_when: no
      loop: >-
        {{ cobbler_profiles
           | selectattr('state', 'equalto', 'present')
           | list }}
      loop_control:
        loop_var: cobbler_profile
        label: "{{ cobbler_profile.name }}"
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::profiles
