---
# Read profiles

- block:
    - name: Search profiles config files
      find:
        paths: "{{ cobbler_config_dir }}/profiles"
        file_type: file
      register: cobbler_search_profiles_config_files_result

    - name: Read profiles config files
      shell: "cat {{ cobbler_profile_config_file }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_profiles_config_result
      changed_when: no
      loop: >-
        {{ cobbler_search_profiles_config_files_result.files
           | map(attribute="path")
           | list }}
      loop_control:
        loop_var: cobbler_profile_config_file
        label: "{{ (cobbler_profile_config_file | basename | splitext).0 }}"

    - name: Read profiles autoinstall files
      shell: "cat {{ cobbler_autoinstall_file_path }} 2>/dev/null || echo ''"
      args:
        warn: no
      register: cobbler_read_autoinstalls_result
      failed_when: no
      changed_when: no
      loop: >-
        {{ cobbler_profiles
           | selectattr('state', 'equalto', 'present')
           | list }}
      loop_control:
        loop_var: cobbler_profile
        label: "{{ cobbler_profile.name }}"

    - name: Setup fact with saved profiles info
      set_fact:
        _cobbler_saved_profiles: >-
          {{ lookup('template', 'saved_profiles.yml.j2') | from_yaml }}

    - name: Setup fact with saved kickstarts info
      set_fact:
        _cobbler_saved_autoinstalls: >-
          {{ lookup('template', 'saved_autoinstalls.yml.j2') | from_yaml }}

    - name: Setup fact with updated profiles info
      set_fact:
        _cobbler_updated_profiles: >-
          {{ lookup('template', 'updated_profiles.yml.j2') | from_yaml }}
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::profiles
