---
# Configure cobbler tasks

- name: Configure cobbler selinux
  include_tasks: selinux.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::selinux

- name: Configure cobbler settings
  include_tasks: settings.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings

- name: Configure cobbler service
  include_tasks: service.yml
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::service
