---
# Configure service tasks

- block:
    - name: Configure cobbler selinux booleans
      seboolean:
        name: "{{ cobbler_selinux_bool }}"
        state: yes
        persistent: yes
      loop: "{{ cobbler_selinux_booleans }}"
      loop_control:
        loop_var: cobbler_selinux_bool
      when: ansible_facts.selinux.status == "enabled"

    - name: Enable and start cobblerd service
      service:
        name: cobblerd
        state: started
        enabled: yes

    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - synchronize:
        src: /usr/share/syslinux/
        dest: /var/lib/cobbler/loaders
        archive: yes
        delete: yes
      delegate_to: "{{ inventory_hostname }}"

    # - name: Download cobbler loaders
    #   command: cobbler get-loaders
    #   register: cobbler_rsync_result
    #   changed_when: cobbler_rsync_result.stdout is search("downloading")

    - meta: flush_handlers
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::service
