---
#  Setup cobbler settings files

- block:
    - name: Configure /etc/cobbler/settings
      template:
        src: settings.j2
        dest: "{{ cobbler_main_config_dir }}/settings"
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify:
        - update signature
        - restart cobblerd

    - name: Configure /etc/cobbler/modules.conf
      template:
        src: modules.conf.j2
        dest: "{{ cobbler_main_config_dir }}/modules.conf"
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart cobblerd

    - name: Setup signatures
      copy:
        dest: "{{ cobbler_signatures_path }}"
        content: "{{ cobbler_signatures | to_nice_json }}"
      when: cobbler_signatures is defined
      notify:
        - restart cobblerd

    - name: Configure /etc/debmirror.conf
      template:
        src: debmirror.conf.j2
        dest: /etc/debmirror.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart cobblerd

    - name: Generate apache ssl certs
      command: /usr/libexec/httpd-ssl-gencerts
      args:
        creates: /etc/pki/tls/certs/localhost.crt
  tags:
    - role::cobbler
    - role::cobbler::configure
    - role::cobbler::configure::settings
